# Generated by Django 6.0.5 on 2026-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_moderation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fake_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='predicted_label',
            field=models.IntegerField(blank=True, db_index=True, help_text='0=real, 1=fake', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='predicted_tag',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='predicted_tag_vi',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
